version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    env_file: .env.development
    # environment:
    #   - MONGO_USERNAME=$MONGO_USERNAME
    #   - MONGO_PASSWORD=$MONGO_PASSWORD
    #   - MONGO_HOSTNAME=db
    #   - MONGO_PORT=$MONGO_PORT
    #   - MONGO_DB=$MONGO_DB
    ports:
      - "5000:5000"
    volumes:
      # https://devopsheaven.com/docker/docker-compose/volumes/2018/01/16/volumes-in-docker-compose.html
      # Syntax: /host/path:/container/path
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network
  db:
    image: mongo:latest
    container_name: db
    restart: unless-stopped
    # env_file: .env
    # If you want to add basic auth set the following
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - 27017:27017
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
